### ISSUE TITLE
The Readme file is misleading

### ISSUE THREAD

**Issue by halbtale** [MattiaGaspa/UniLabCpp#1]
#### Description
The README file currently contains an outdated course title:
> "Raccolta di programmi utilizzati per il corso di Dati e Algoritmi"

#### Suggested Correction
Update the course title to:
> "Raccolta di programmi utilizzati per il corso di Laboratorio di Programmazione"

#### Tasks
- Update the README file to reflect the correct course title.

#### Additional Notes
This change is to ensure clarity and consistency with the current course name.

**Comment by MattiaGaspa** [comment]
**Completed tasks**:

- Update the README file to reflect the correct course title.
- (to ensure even more clarity and consistency) Updated the about section of the repository
